---
- name: Generate ACL initial management token
  shell: openssl rand -base64 16
  register: acl_token
  run_once: true
  when: consul_mode == "server"
  become: no

- name: Save ACL token locally
  copy:
    content: "{{ acl_token.stdout }}"
    dest: "{{ playbook_dir }}/consul_acl_token.txt"
    mode: '0600'
  when: consul_mode == "server"
  become: no
  run_once: true
  delegate_to: localhost

- name: Read ACL token
  set_fact:
    consul_acl_token: "{{ lookup('file', playbook_dir + '/consul_acl_token.txt') }}"
