plugin: amazon.aws.aws_ec2
# aws_profile: iac

regions:
  - eu-north-1

groups:
  lb: "'lb' in tags.Name"
  db: "'db' in tags.Name"
  app: "'app' in tags.Name"
  consul: "'consul' in tags.Name"

keyed_groups:
  - key: tags.Environment
    prefix: tag_Environment
